import React, { Fragment } from 'react'

const cityselect = () => {
  return (
    <Fragment>
        <label className="labelsppl" htmlFor='zona_influencia'>Zona a la que desea contribuir</label>
        <select className="inputs-text-ppl" id="grid-zona"  name='zona_influencia' type='text' required>
            <option value="">Selecciona una opción...</option>   
            <option value="ABEJORRAL">ABEJORRAL</option>
            <option value="ABRIAQUI">ABRIAQUI</option>
            <option value="ALEJANDRIA">ALEJANDRIA</option>
            <option value="AMAGA">AMAGA</option>
            <option value="AMALFI">AMALFI</option>
            <option value="ANDES">ANDES</option>
            <option value="ANGELOPOLIS">ANGELOPOLIS</option>
            <option value="ANGOSTURA">ANGOSTURA</option>
            <option value="ANORI">ANORI</option>
            <option value="ANZA">ANZA</option>
            <option value="APARTADO">APARTADO</option>
            <option value="ARBOLETES">ARBOLETES</option>
            <option value="ARGELIA">ARGELIA</option>
            <option value="ARMENIA">ARMENIA</option>
            <option value="BARBOSA">BARBOSA</option>
            <option value="BELLO">BELLO</option>
            <option value="BELMIRA">BELMIRA</option>
            <option value="BETANIA">BETANIA</option>
            <option value="BETULIA">BETULIA</option>
            <option value="BRICEÑO">BRICEÑO</option>
            <option value="BURITICA">BURITICA</option>
            <option value="CACERES">CACERES</option>
            <option value="CAICEDO">CAICEDO</option>
            <option value="CALDAS">CALDAS</option>
            <option value="CAMPAMENTO">CAMPAMENTO</option>
            <option value="CAÑASGORDAS">CAÑASGORDAS</option>
            <option value="CARACOLI">CARACOLI</option>
            <option value="CARAMANTA">CARAMANTA</option>
            <option value="CAREPA">CAREPA</option>
            <option value="CARMEN DE VIBORAL">CARMEN DE VIBORAL</option>
            <option value="CAROLINA">CAROLINA</option>
            <option value="CAUCASIA">CAUCASIA</option>
            <option value="CHIGORODO">CHIGORODO</option>
            <option value="CISNEROS">CISNEROS</option>
            <option value="CIUDAD BOLIVAR">CIUDAD BOLIVAR</option>
            <option value="COCORNA">COCORNA</option>
            <option value="CONCEPCION">CONCEPCION</option>
            <option value="CONCORDIA">CONCORDIA</option>
            <option value="COPACABANA">COPACABANA</option>
            <option value="DABEIBA">DABEIBA</option>
            <option value="DON MATIAS">DON MATIAS</option>
            <option value="EBEJICO">EBEJICO</option>
            <option value="EL BAGRE">EL BAGRE</option>
            <option value="ENTRERRIOS">ENTRERRIOS</option>
            <option value="ENVIGADO">ENVIGADO</option>
            <option value="FREDONIA">FREDONIA</option>
            <option value="FRONTINO">FRONTINO</option>
            <option value="GIRALDO">GIRALDO</option>
            <option value="GIRARDOTA">GIRARDOTA</option>
            <option value="GOMEZ PLATA">GOMEZ PLATA</option>
            <option value="GRANADA">GRANADA</option>
            <option value="GUADALUPE">GUADALUPE</option>
            <option value="GUARNE">GUARNE</option>
            <option value="GUATAPE">GUATAPE</option>
            <option value="HELICONIA">HELICONIA</option>
            <option value="HISPANIA">HISPANIA</option>
            <option value="ITAGUI">ITAGUI</option>
            <option value="ITUANGO">ITUANGO</option>
            <option value="JARDIN">JARDIN</option>
            <option value="JERICO">JERICO</option>
            <option value="LA CEJA">LA CEJA</option>
            <option value="LA ESTRELLA">LA ESTRELLA</option>
            <option value="LA PINTADA">LA PINTADA</option>
            <option value="LA UNION">LA UNION</option>
            <option value="LIBORINA">LIBORINA</option>
            <option value="MACEO">MACEO</option>
            <option value="MARINILLA">MARINILLA</option>
            <option value="MEDELLIN">MEDELLIN</option>
            <option value="MONTEBELLO">MONTEBELLO</option>
            <option value="MURINDO">MURINDO</option>
            <option value="MUTATA">MUTATA</option>
            <option value="NARIÑO">NARIÑO</option>
            <option value="NECHI">NECHI</option>
            <option value="NECOCLI">NECOCLI</option>
            <option value="OLAYA">OLAYA</option>
            <option value="PEÑOL">PEÑOL</option>
            <option value="PEQUE">PEQUE</option>
            <option value="PUEBLORRICO">PUEBLORRICO</option>
            <option value="PUERTO BERRIO">PUERTO BERRIO</option>
            <option value="PUERTO NARE">PUERTO NARE</option>
            <option value="PUERTO TRIUNFO">PUERTO TRIUNFO</option>
            <option value="REMEDIOS">REMEDIOS</option>
            <option value="RETIRO">RETIRO</option>
            <option value="RIONEGRO">RIONEGRO</option>
            <option value="SABANALARGA">SABANALARGA</option>
            <option value="SABANETA">SABANETA</option>
            <option value="SALGAR">SALGAR</option>
            <option value="SAN ANDRES">SAN ANDRES</option>
            <option value="SAN CARLOS">SAN CARLOS</option>
            <option value="SAN FRANCISCO">SAN FRANCISCO</option>
            <option value="SAN JERONIMO">SAN JERONIMO</option>
            <option value="SAN JOSE DE LA MONTAÑA">SAN JOSE DE LA MONTAÑA</option>
            <option value="SAN JUAN DE URABA">SAN JUAN DE URABA</option>
            <option value="SAN LUIS">SAN LUIS</option>
            <option value="SAN PEDRO">SAN PEDRO</option>
            <option value="SAN PEDRO DE URABA">SAN PEDRO DE URABA</option>
            <option value="SAN RAFAEL">SAN RAFAEL</option>
            <option value="SAN ROQUE">SAN ROQUE</option>
            <option value="SAN VICENTE">SAN VICENTE</option>
            <option value="SANTA BARBARA">SANTA BARBARA</option>
            <option value="SANTA ROSA DE OSOS">SANTA ROSA DE OSOS</option>
            <option value="SANTAFE DE ANTIOQUIA">SANTAFE DE ANTIOQUIA</option>
            <option value="SANTO DOMINGO">SANTO DOMINGO</option>
            <option value="SANTUARIO">SANTUARIO</option>
            <option value="SEGOVIA">SEGOVIA</option>
            <option value="SONSON">SONSON</option>
            <option value="SOPETRAN">SOPETRAN</option>
            <option value="TAMESIS">TAMESIS</option>
            <option value="TARAZA">TARAZA</option>
            <option value="TARSO">TARSO</option>
            <option value="TITIRIBI">TITIRIBI</option>
            <option value="TOLEDO">TOLEDO</option>
            <option value="TURBO">TURBO</option>
            <option value="URAMITA">URAMITA</option>
            <option value="URRAO">URRAO</option>
            <option value="VALDIVIA">VALDIVIA</option>
            <option value="VALPARAISO">VALPARAISO</option>
            <option value="VEGACHI">VEGACHI</option>
            <option value="VENECIA">VENECIA</option>
            <option value="VIGIA DEL FUERTE">VIGIA DEL FUERTE</option>
            <option value="YALI">YALI</option>
            <option value="YARUMAL">YARUMAL</option>
            <option value="YOLOMBO">YOLOMBO</option>
            <option value="YONDO">YONDO</option>
            <option value="ZARAGOZA">ZARAGOZA</option>
        </select>
    </Fragment>
  )
}

export default cityselect